version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: "Dockerfile.dev"
    restart: unless-stopped
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./backend/src:/usr/src/app/src
    networks:
      - backend

  db:
    image: "mongo:4"
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    ports:
      - "27018:27017"
    networks:
      - backend

volumes:
  mongoconfig:
    external: false

  mongodata:
    external: false

networks:
  backend:
